{
  try {
    callback.call();
  }
 catch (  Exception e) {
  }
}
